#!/bin/sh

while read -r file; do
	case "$1" in
	"w")
		setbg "$file" &
		;;
	"W")
		cwebp "$file" -sns 100 -sharp_yuv -f 100 -pass 10 -af -mt -m 6 -o "${file%.*}.webp" &
		;;
	"c")
		[ -z "$destdir" ] && destdir="$(listmarks dirs | dmenu -l 20 -i -p "Copy file(s) to where?")"
		[ ! -d "$destdir" ] && notify-send "${0##*/}" "$destdir is not a directory, cancelled." && exit
		cp -- "$file" "$destdir" && notify-send -i "$destdir/${file##*/}" "${0##*/}" "${file##*/} copied to $destdir." &
		;;
	"m")
		[ -z "$destdir" ] && destdir="$(listmarks dirs | dmenu -l 20 -i -p "Move file(s) to where?")"
		[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
		mv -- "$file" "$destdir" && notify-send -i "$destdir/${file##*/}" "${0##*/}" "${file##*/} moved to $destdir." &
		;;
	"r")
		convert -rotate 90 "$file" "$file"
		;;
	"R")
		convert -rotate -90 "$file" "$file"
		;;
	"f")
		convert -flop "$file" "$file"
		;;
	"I")
		convert "$file" -channel RGB -negate "$file"
		;;
	"y")
		printf -- "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
			notify-send "$file copied to clipboard" &
		;;
	"Y")
		readlink -f -- "$file" | tr -d '\n' | xclip -selection clipboard &&
			notify-send "$(readlink -f -- "$file") copied to clipboard" &
		;;
	"d")
		if gio trash -- "$file" || trash-put -- "$file"; then
			notify-send "${0##*/}" "${file##*/} moved to trash." &
		elif [ -f "$file" ] && [ "$(printf -- 'No\nYes' | dmenu -i -p "Really delete $file?")" = "Yes" ]; then
			if rm -- "$file"; then
				notify-send "${0##*/}" "${file##*/} deleted." &
			else
				notify-send --urgency=critical "Error" "'$file' wasn't deleted." &
			fi
		fi
		;;
	"g")
		ifinstalled gimp && setsid -f gimp "$file"
		;;
	"i")
		notify-send "File information" "$(mediainfo -- "$file")"
		;;
	*)
		notify-send "${0##*/}" "$1 is not bound."
		;;
	esac
done
