include current-theme.conf

background       #2f343f
foreground       #f1fcf9
font_family      Hack
font_size        11.0
scrollback_lines 20000

# https://github.com/kovidgoyal/kitty/issues/4793
# https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.close_on_child_death
close_on_child_death yes

map ctrl+shift+h launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay nvim
map ctrl+t new_tab_with_cwd

# Makes new kitty launches reuse the existing instance, like urxvtd/urxvtc.
single_instance yes
