#!/bin/bash

# https://github.com/jstkdng/ueberzugpp/blob/master/scripts/lf/preview
# https://github.com/gokcehan/lf/wiki/Previews

# File preview handler for lf.

set -euo pipefail
set -C -f

readonly FILE=$1
readonly W=$2
readonly MW=$(( $2 - 1 ))
readonly H=$3
readonly MH=$(( $3 - 1 ))
readonly X=$4
readonly Y=$5

if [[ ${FILE} == *'.!qB' ]]; then
	exit
fi

IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

killall mediainfo || true

is_installed() {
	[[ -x "$(command -v "$1")" ]]
}

has_ueberzug() {
	[[ -n "${FIFO_UEBERZUG:-}" ]] && is_installed ueberzug
}

has_ueberzugpp() {
	is_installed ueberzugpp
}

if has_ueberzug; then
	printf -- '{"action": "remove", "identifier": "PREVIEW"}\n' > "$FIFO_UEBERZUG"
elif has_ueberzugpp; then
	ueberzugpp cmd -s "$UB_SOCKET" -a remove -i PREVIEW
fi

kitten_draw() {
	kitten icat --stdin no --transfer-mode memory --engine builtin \
		--place "${MW}x${MH}@${X}x${Y}" "$1" </dev/null >/dev/tty
}

ueberzug_preview() {
	if [[ $TERM == *kitty ]]; then
		kitten_draw "$1"
	elif [[ $TERM == contour ]]; then
		chafa -f sixel -s "${MW}x${MH}" \
			--animate off --polite on -t 1 --bg black \
			"$1"
	elif has_ueberzugpp; then
		ueberzugpp cmd -s "$UB_SOCKET" -a add -i PREVIEW -x "$X" -y "$Y" \
			--max-width "$MW" --max-height "$MH" -f "$1"
	elif has_ueberzug; then
		printf -- '{
			"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s",
			"width": "%s", "height": "%s", "scaler": "contain", "path": "%s"
		}\n' "$X" "$Y" "$MW" "$MH" "$1" > "$FIFO_UEBERZUG"
	else
		mediainfo "$FILE"
	fi
}

image() {
	if [[ -f "$1" ]] && [[ -n "${DISPLAY:-}" ]] && [[ -z "${WAYLAND_DISPLAY:-}" ]]; then
		ueberzug_preview "$1"
	else
		mediainfo "$FILE"
	fi
}

batorcat() {
	local -r file="$1"
	shift

	bat_args=( --line-range :100 --style=plain --pager=never "$@" -- "$file")
	if is_installed bat; then
		bat    "${bat_args[@]}"
	elif is_installed batcat; then
		batcat "${bat_args[@]}"
	else
		echo "bat is not installed. using cat."
		head -100 -- "$file"
	fi
}

# Note that the cache file name is a function of file information, meaning if
# an image appears in multiple places across the machine, it will not have to
# be regenerated once seen.

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f -- "$FILE")" | sha256sum | cut -d' ' -f1).jpg"
mime_type=$( file --dereference --brief --mime-type -- "$FILE" )
readonly CACHE mime_type
case "$mime_type" in
	image/avif)
		if [[ ! -f "$CACHE" ]]; then magick "$FILE" "$CACHE"; fi
		image "$CACHE" "$W" "$H" "$X" "$Y" "$FILE" ;;
	image/vnd.djvu)
		if [[ ! -f "$CACHE" ]]; then djvused "$FILE" -e 'select 1; save-page-with /dev/stdout' | magick -density 200 - "$CACHE" > /dev/null 2>&1; fi
		image "$CACHE" "$W" "$H" "$X" "$Y" "$FILE" ;;
	image/svg+xml)
		if [[ ! -f "$CACHE" ]]; then inkscape --convert-dpi-method=none -o "$CACHE.png" --export-overwrite -D --export-png-color-mode=RGBA_16 "$FILE"; fi
		image "$CACHE.png" "$W" "$H" "$X" "$Y" "$FILE"
		;;
	image/x-xcf)
		if [[ ! -f "$CACHE" ]]; then magick "$1[0]" "$CACHE"; fi
		image "$CACHE" "$W" "$H" "$X" "$Y" "$FILE"
		;;
	image/*)
		image "$FILE" "$W" "$H" "$X" "$Y" "$FILE" ;;
	text/html)
		lynx -width="$X" -display_charset=utf-8 -dump "$FILE" ;;
	text/troff)
		man ./ "$FILE" | col -b ;;
	text/* | */xml | application/json | application/x-ndjson)
		batorcat "$FILE" --terminal-width "$(( X - 2 ))" --theme ansi --force-colorization ;;
	audio/* | application/octet-stream | *djvu)
		mediainfo "$FILE"
		;;
	video/* )
		if [[ ! -f "$CACHE" ]]; then ffmpegthumbnailer -s 0 -i "$FILE" -o "$CACHE"; fi
		image "$CACHE" "$W" "$H" "$X" "$Y" "$FILE"
		;;
	*/pdf)
		if [[ ! -f "$CACHE" ]]; then pdftoppm -jpeg -f 1 -singlefile "$FILE" "$CACHE"; fi
		image "$CACHE" "$W" "$H" "$X" "$Y" "$FILE"
		;;
	*/epub+zip|*/mobi*)
		if [[ ! -f "$CACHE" ]]; then gnome-epub-thumbnailer "$FILE" "$CACHE"; fi
		image "$CACHE" "$W" "$H" "$X" "$Y" "$FILE"
		;;
	application/*zip | application/*tar)
		atool --list -- "$FILE" ;;
	*opendocument*)
		odt2txt "$FILE" ;;
	application/pgp-encrypted)
		gpg -d -- "$FILE" ;;
	*)
		echo "Unknown file type: $mime_type"
		batorcat "$FILE" --color=always
		;;
esac
exit 1
