#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \
	:q="exit" \
	help="man" \
	chd='cd -- "$(choose_from_cwds)" && ls -a' \
	rclone="rclone -v" \

# Youtube
alias \
	yt="yt-dlp --embed-metadata -i" \
	ytautosub="yt --write-auto-sub --sub-lang ja" \
	yta="yt -x -f bestaudio/best" \
	mp3dl="yta --audio-quality 1 --audio-format mp3" \
	ytv="youtube-viewer" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \

# Other stuff
alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	tmux="tmux -f \${XDG_CONFIG_HOME:-\$HOME/.config}/tmux/tmux.conf" \
	timer='echo "Timer started. Stop with Ctrl-D." && date "+%a, %d %b %H:%M:%S" && time cat && date "+%a, %d %b %H:%M:%S"' \
	updxrdb="xrdb -merge \${XDG_CONFIG_HOME:-\$HOME/.config}/Xresources" \
	genpasswd="openssl rand -base64 21" \
	update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
	trim="sudo fstrim -v / && sudo fstrim -v /home" \
	showpath="echo \$PATH | sed 's/:/\n/g'" \
	visoodoo="sudo visudo -f /etc/sudoers.d/01_sudoers" \
	res_screencast="xrandr --output DP1 --primary --mode 1920x1080" \
	res_normal="xrandr --output DP1 --primary --mode 1920x1200" \

# dotfiles in git
# https://wiki.archlinux.org/index.php/Dotfiles
# or use ~/.git/info/exclude
alias dot='git --git-dir=${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/ --work-tree=$HOME'

# Journal
alias \
	journal="journalctl --since '3 day ago'" \
	errors="journalctl -p err..alert -b -e" \

# Applications
alias \
	clock="ncmpcpp -s clock" \
	visualizer="ncmpcpp -s visualizer" \
	nb="newsboat" \
	getmail="offlineimap && notmuch new" \
	gm="offlineimap && notmuch new" \
	nf="clear && neofetch" \
	kakasi_reading="kakasi -i utf8 -o utf8 -u -JH -KH" \

# Pacman / system
basepac='bash bzip2 coreutils file filesystem findutils gawk gcc-libs gettext glibc grep gzip iproute2 iputils licenses pacman pciutils procps-ng psmisc sed shadow systemd systemd-sysvcompat tar util-linux xz'

alias \
	lsp="pacman -Qett --color=always | less" \
	notify-pacman-block="pkill -RTMIN+8 i3blocks" \
	upd="archnews && trizen -Syu && notify-pacman-block" \
	trimlogs='sudo journalctl --vacuum-size=150M' \
	pacclean="remorphans && sudo pacman -Sc && trimlogs" \
	whathaveidone="tail -500 /var/log/pacman.log | grep -i 'installed\|removed\|graded' --color=never" \
	refl='sudo reflector --protocol https --download-timeout 60 --verbose --age 6 --latest 100 --fastest 10 --sort rate --country "$(curl -Ls "ifconfig.co/country"),DE,FR,GB,NL,PL,RU,BY,CZ,FI,SE,CH,HU,NO" --save /etc/pacman.d/mirrorlist' \
	reflp='sudo reflector --url "https://www.parabola.nu/mirrors/status/json" --protocol https --download-timeout 60 --verbose --age 12 --latest 100 --fastest 10 --sort rate --save /etc/pacman.d/parabola-mirrorlist' \
	all_but_base="comm -23 <(pacman -Qetq | sort) <({ pacman -Qgq base-devel ; echo \$basepac | tr ' ' '\n' ;} | sort) | less" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	printsrcinfo="makepkg --printsrcinfo > .SRCINFO" \
	unlockme='faillock --user "$USER" --reset' \
	listkernels='ls -1 /boot/vmli*' \
	egit='sudo etckeeper vcs' \
