#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx='startx $XINITRC'

[ -f "$MBSYNCRC" ] && alias mbsync='mbsync -c $MBSYNCRC'

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \
	:q="exit" \
	help="man" \
	chd='cd -- "$(choose_from_cwds)" && ls -a' \
	rclone="rclone -v" \

# Youtube
alias \
	ytd="yt-dlp --embed-metadata -i" \
	ytautosub="ytd --write-auto-sub --sub-lang ja" \
	yta="ytd -x -f bestaudio/best" \
	mp3dl="yta --audio-quality 1 --audio-format mp3" \
	ytv="youtube-viewer" \
	ytt="ytd --skip-download --write-thumbnail" \
	ytw="ytd --merge-output-format webm -f 'bestvideo[ext=webm]+bestaudio/best[ext=webm]'" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	ggrep="grep --exclude-dir='.git' --exclude-dir='.mypy_cache'" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \

# Other stuff
alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	tmux="tmux -f \${XDG_CONFIG_HOME}/tmux/tmux.conf" \
	timer='echo "Timer started. Stop with Ctrl-D." && date "+%a, %d %b %H:%M:%S" && time cat && date "+%a, %d %b %H:%M:%S"' \
	updxrdb="xrdb -merge \${XDG_CONFIG_HOME}/Xresources" \
	genpasswd="openssl rand -base64 21" \
	update-grub="sudo grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB --recheck ; sudo grub-mkconfig -o /boot/grub/grub.cfg" \
	trim="sudo fstrim -v / && sudo fstrim -v /home" \
	showpath="echo \$PATH | sed 's/:/\n/g'" \
	visoodoo="sudo visudo -f /etc/sudoers.d/01_sudoers" \
	res_screencast="xrandr --output DP1 --primary --mode 1920x1080" \
	res_normal="xrandr --output DP1 --primary --mode 1920x1200" \
	charm="setsid -f pycharm . ; sleep 3s ; exit" \

# dotfiles in git
# https://wiki.archlinux.org/index.php/Dotfiles
# or use ~/.git/info/exclude
alias dot='git --git-dir=${XDG_CONFIG_HOME}/dotfiles/ --work-tree=$HOME'

# Journal
alias \
	journal="journalctl --since '3 day ago'" \
	errors="journalctl -p err..alert -b -e" \

# Applications
alias \
	clock="ncmpcpp -s clock" \
	visualizer="ncmpcpp -s visualizer" \
	nb="newsboat" \
	getmail="offlineimap && notmuch new" \
	gm="offlineimap && notmuch new" \
	nf="clear && neofetch" \
	kakasi_reading="kakasi -i utf8 -o utf8 -u -JH -KH" \

# Morphological analysis

alias \
	mecabfurigana="my_mecab '--node-format=%m[%f[7]] ' '--eos-format=\n' '--unk-format=%m '" \
	mecabanalyze="my_mecab '--node-format=%m,%f[6],%f[7],%f[0],%f[5]\n' '--unk-format=%m\n' '--eos-format=\n'" \

# Pacman / system

alias \
	lsp="pacman -Qett --color=always | less" \
	notify-pacman-block="pkill -RTMIN+8 i3blocks" \
	upd="sb-popupgrade --no-wait" \
	trimlogs='sudo journalctl --vacuum-size=150M' \
	pacclean="remorphans && sudo pacman -Sc && trimlogs" \
	whathaveidone="tail -500 /var/log/pacman.log | grep -i 'installed\|removed\|graded' --color=never" \
	refl='sudo reflector --protocol https --download-timeout 60 --verbose --age 6 --latest 100 --fastest 10 --sort rate --country "$(curl -Ls "ifconfig.co/country")" --save /etc/pacman.d/mirrorlist' \
	reflp='sudo reflector --url "https://www.parabola.nu/mirrors/status/json" --protocol https --download-timeout 60 --verbose --age 12 --latest 100 --fastest 10 --sort rate --save /etc/pacman.d/parabola-mirrorlist' \
	printsrcinfo="makepkg --printsrcinfo > .SRCINFO" \
	unlockme='faillock --user "$USER" --reset' \
	listkernels='ls -1 /boot/vmli*' \
	egit='sudo etckeeper vcs' \
	te='gio trash --empty' \
	ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutenvrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc'
	hogs='ps axch -o cmd:15,%mem --sort=-%mem | head -20' \
