#!/bin/zsh

# https://wiki.archlinux.org/index.php/Zsh
# http://zsh.sourceforge.net/FAQ/
# The  personal initialization file, executed for login shells.
# It is loaded when you login. Read only once.
# shellcheck disable=SC2155

# Sway startup function
startsway () {
	export GDK_BACKEND=wayland
	export CLUTTER_BACKEND=wayland
	export XKB_DEFAULT_LAYOUT=us,ru
	export XKB_DEFAULT_MODEL=pc104
	export XKB_DEFAULT_VARIANT=altgr-intl,winkeys
	export XKB_DEFAULT_OPTIONS=grp:win_space_toggle,terminate:ctrl_alt_bksp,caps:escape
	exec sway
}

unsetopt PROMPT_SP

# Default programs:
export WM="i3"
export STATUSBAR="${WM}blocks"
export EDITOR="nvim"
export TERMINAL="alacritty"
export TERMINAL_PROG=$TERMINAL
export BROWSER="fingerbox"
export READER="zathura"
export FILE="lfub"

# Change the default crypto/weather monitor sites.
# export CRYPTOURL="rate.sx"
# export WTTRURL="wttr.in"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
#export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_DATA_HOME/history"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"

# Other program settings:
export GEM_HOME="$(ruby -e 'puts Gem.user_dir' 2>/dev/null)"
export LANG="en_US.UTF-8"
export TERM="xterm-256color"
export LESS='-F -i -J -M -R -W -x4 -X -z-4' # https://www.topbug.net/blog/2016/09/27/make-gnu-less-more-powerful/
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export MOZ_USE_XINPUT2="1" # Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D" # May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for Java applications in dwm
export TDESKTOP_USE_GTK_FILE_DIALOG=1

# TSP settings
# https://aur.archlinux.org/packages/task-spooler/
export TS_SLOTS=10		# the maximum number of jobs running at once with task-spooler.
export TS_ONFINISH=tsp_onfinish	# run by the client after the  queued  job.

# Speed up compile times
# https://wiki.archlinux.org/index.php/Makepkg#Creating_optimized_packages
MAKEFLAGS="-j$(($(nproc) + 1)) -l$(nproc)"; export MAKEFLAGS
export CFLAGS="-Wall -Wextra -Wpedantic -Wconversion -Wshadow -march=native -O2 -pipe -fstack-protector-strong -fno-plt"
export CXXFLAGS="$CFLAGS"

# Fix QT themes on GTK Desktops
# https://tatsumoto.neocities.org/blog/setting-up-anki.html#gtk-theme
export QT_QPA_PLATFORMTHEME=qt6ct

# Fix QT plugin path for pyqt packages installed with pip.
export QT_PLUGIN_PATH=/usr/lib/qt/plugins:$(find ~/.local/lib/ -type d -wholename '*/python3*/site-packages/PyQt*/plugins' | paste -s -d :)

# Fix Java programs
# https://wiki.archlinux.org/index.php/Java_Runtime_Environment_fonts
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'

if [[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ]]; then
	setsid shortcuts >/dev/null 2>&1
fi

# Adds `~/.local/bin/` and all subdirectories to $PATH
if [[ -d "$HOME/.local/bin/" ]]; then
	PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
fi
if [[ -n $GEM_HOME ]] && [[ -d "$GEM_HOME/bin" ]]; then
	PATH="$PATH:$GEM_HOME/bin"
fi
if [[ -d "$HOME/.local/share/cargo/bin" ]]; then
	PATH="$PATH:$HOME/.local/share/cargo/bin"
fi
export PATH

# Start graphical server on tty1 if not already running.
# https://wiki.archlinux.org/index.php/Xinit#Autostart_X_at_login
if [[ -z "${DISPLAY}" ]] && [[ "${XDG_VTNR}" -eq 1 ]]; then
	exec startx "$XINITRC"
fi

if [[ "$(tty)" == "/dev/tty2" ]]; then
	exec startsway
fi

# Switch escape and caps if tty and no passwd required:
sudo -n loadkeys "${XDG_DATA_HOME:-$HOME/.local/share}/larbs/ttymaps.kmap" 2>/dev/null
