#!/bin/sh

# Fcitx
# https://wiki.archlinux.org/index.php/Fcitx
find_fcitx() {
	for cmd in fcitx5 fcitx; do
		command -v "$cmd" && return
	done
}

if [ -n "${fcitx:=$(find_fcitx)}" ]; then
	# Define the environment variables to register the input method modules.
	export GTK_IM_MODULE=fcitx
	export QT_IM_MODULE=fcitx
	export XMODIFIERS=@im=fcitx
	setxkbmap -model pc104 \
		  -layout us \
		  -variant altgr-intl \
		  -option terminate:ctrl_alt_bksp,caps:escape
	"$fcitx" -dr &
else
	setxkbmap -model pc104 \
		  -layout us,ru \
		  -variant altgr-intl,winkeys \
		  -option terminate:ctrl_alt_bksp,caps:escape,grp:win_space_toggle
fi
