#!/bin/sh

# Fcitx
# https://wiki.archlinux.org/index.php/Fcitx
find_fcitx() {
	for cmd in fcitx5 fcitx; do
		if [ -x "$(command -v "$cmd")" ]; then
			echo "$cmd"
			return
		fi
	done
}

if [ -n "${fcitx:=$(find_fcitx)}" ]; then
	# Define the environment variables to register the input method modules.
	export GTK_IM_MODULE=fcitx
	export QT_IM_MODULE=fcitx
	export XMODIFIERS=@im=fcitx

	# kitty workaround
	# https://github.com/kovidgoyal/kitty/issues/469#issuecomment-778814173
	export GLFW_IM_MODULE=ibus

	setxkbmap -model pc104 \
		  -layout us \
		  -variant altgr-intl \
		  -option terminate:ctrl_alt_bksp,caps:escape
	# run fcitx from i3's config: ~/.config/i3/config, or here: "$fcitx" 2>/dev/null &
else
	setxkbmap -model pc104 \
		  -layout us,ru \
		  -variant altgr-intl,winkeys \
		  -option terminate:ctrl_alt_bksp,caps:escape,grp:win_space_toggle
fi
