#!/bin/sh

# xinitrc runs automatically when you run startx.
# https://wiki.archlinux.org/index.php/Xinit#xinitrc
export GDK_BACKEND=x11
export XDG_SESSION_TYPE=x11

# https://forum.manjaro.org/t/how-to-theme-gtk4-apps-in-manjaro-xfce/100189/7
# https://forum.manjaro.org/t/setting-theme-for-gtk4-applications/165845
export GTK_THEME='Arc-Darker'

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		# shellcheck source=/dev/null
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# There are some small but important commands that need to be run
# when we start the graphical environment.
# shellcheck source=/dev/null
. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"

# Activate dbus variables
dbus-update-activation-environment --all

# Your default WM is determined in your `~/.profile` on login.
# Here we run the proper command to run when the graphical environment starts.
dbus-launch ssh-agent "${WM:-i3}"
