#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Monitor configuration (arandr)
# NOTE: use autorandr
# autorandr -c --default default &
# NOTE: autorandr is started by systemd

# Set DPI. User may want to use a larger number for larger screens.
xrandr --dpi 96

# Pipewire uses systemd/User for management of the server and automatic socket activation
# so you don't need to do anything because it starts automatically when needed.
#if ! systemctl --quiet --user is-enabled pipewire; then
#	systemctl --user --now enable pipewire pipewire-pulse wireplumber
#fi

# Keyboard layouts
# If fcitx is installed, it will be used.
. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/keyboard_layouts"

# Remap keys like Caps and Super
remapd &

# Xcompmgr is a simple compositor capable of rendering drop shadows and, with the use of the transset utility, primitive window transparency.
xcompmgr &

# Use Xresources colors/settings on startup
xrdb -merge "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"

# Set the background with the `setbg` script
setbg &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
