#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
# Set DPI. User may want to use a larger number for larger screens.
xrandr --dpi 96
# Set the background with the `setbg` script
setbg &
# File synchronization
syncthing -no-browser &
# Backups. Install deja-dup.
/usr/lib/deja-dup/deja-dup-monitor &
# Podboat automatic queue and download. Requires entr.
podentr &
# Run mailsync periodically
{ command -v mailsync && while :; do mailsync; sleep 15m; done; } &
# Rank invidious and nitter instances
rank-invidious-instances >/dev/null &
rank-nitter-instances >/dev/null &
# Use Xresources colors/settings on startup
xrdb -merge "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"
# Start a polkit agent to run software like gparted.
lxqt-policykit-agent &

# Autostart
for program in mpd xcompmgr dunst unclutter pipewire remapd; do
	if ! pidof -sx "$program" && command -v "$program"; then
		"$program" &
	fi
done

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
