live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black =   "0x928374"
red =     "0xfb4934"
green =   "0xb8bb26"
yellow =  "0xfabd2f"
blue =    "0x83a598"
magenta = "0xd3869b"
cyan =    "0x8ec07c"
white =   "0xebdbb2"

[colors.cursor]
cursor = "0x4ced4c"
# style = "Block"

[colors.normal]
black =   "0x222d32"
red =     "0xfb4934"
green =   "0x98971a"
yellow =  "0xd79921"
blue =    "0x83a598"
magenta = "0xb16286"
cyan =    "0x689d6a"
white =   "0xfbf1c7"

[colors.primary]
background = "0x222d32"
foreground = "0xf1fcf9"

[env]
#TERM = "xterm-256color"
TERM = "alacritty"

[font]
size = 10.5

[font.normal]
family = "Hack"

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[[hints.enabled]]
command = "linkhandler"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "L"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = '([0-9a-f]{7,128})|([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})|(i-[0-9a-f]{17})'

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0011:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011:"
key = "Semicolon"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011%"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011X"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011o"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011\u000F"
key = "O"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00111"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00112"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00113"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00114"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00115"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00116"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00116"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00117"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00119"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011p"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0011n"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0011w"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011L"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011\b"
key = "Comma"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011\f"
key = "Period"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011["
key = "LBracket"
mods = "Command"

[window]
#decorations = "none"
dynamic_title = true
opacity = 1.0

[window.padding]
x = 2
y = 0
